spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/gamza_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: uijin-mysql-pw

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none

file.dir: "/Users/uijin/Devcourse/project_01/react-springboot-rest-api/shop_gamza/src/main/resources/file/"
